<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	  	<TargetFramework>netstandard2.1</TargetFramework>
	  	<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <Folder Include="Customers\Dtos\" />
	  <Folder Include="IngredientProducts\Dtos\" />
	  <Folder Include="IngredientTypeTemplateSteps\Dtos\" />
	  <Folder Include="OrderProducts\Dtos\" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="BouncyCastle" Version="1.8.9" />
	  <PackageReference Include="itext7" Version="8.0.5" />
	  <PackageReference Include="itext7.bouncy-castle-adapter" Version="8.0.5" />
	  <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="8.0.0" />
	</ItemGroup>
</Project>
  